data:
  phenotype: "data/Phenotype.rda"
  genomic: "data/Genomic.rda"
  localisation: "data/localisation.rda"
  residuals: "Residuals/LM_Pheno_pop_Residuals.rds"

analysis:
  phenotypes:
    - "HT2009"
    - "CIRC2011"
    - "Rust"
    - "CIRC2009"
    - "BudFlushSlope"
    - "RamifSyllep"
    - "BrAnglVert"
    - "Dia2015_sqrt"
  use_residuals: true
  n_iter: 4
  subset_size: 5
  seed: 12345

cv:
  outer_folds: 5

output:
  save_dir: "results/VIP_scores_multi"
