data:
  phenotype: "data/LM_Pheno_pop_Residuals.rda"
  genomic: "data/Genomic.rda"
  localisation: "data/localisation.rda"
analysis:
  phenotype_name: CIRC2009
  n_iter: 8
  subset_size: 50
  seed: 123.0
cv:
  outer_folds: 5
output:
  save_dir: results/RF_CIRC2009_Residuals
