data:
  phenotype: data/Phenotype.rda
  genomic: data/Genomic.rda
  localisation: data/localisation.rda
analysis:
  phenotype_name: Dia2015_sqrt
  n_iter: 870.0
  subset_size: 5000.0
  seed: 123.0
cv:
  outer_folds: 5.0
output:
  save_dir: results/VIP_Dia2015_sqrt
