data:
  phenotype: data/Phenotype.rda
  genomic: data/Genomic.rda
  localisation: data/localisation.rda
analysis:
  phenotype_name: C5_C6
  n_iter: 870.0
  subset_size: 5000.0
  seed: 123.0
cv:
  outer_folds: 6.0
output:
  save_dir: results/RF_C5_C6
